# Generated by Django 4.2.20 on 2025-04-28 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('is_online', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('Conference', 'Conference'), ('Workshop', 'Workshop'), ('Hackathon', 'Hackathon'), ('Meetup', 'Meetup'), ('Webinar', 'Webinar'), ('Other', 'Other')], max_length=50)),
                ('tags', models.JSONField()),
                ('image', models.CharField(max_length=200)),
                ('organizer', models.CharField(max_length=100)),
                ('organizer_image', models.CharField(max_length=200)),
                ('attendees', models.IntegerField(default=0)),
                ('is_free', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('spots_left', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
