# Generated by Django 4.2.20 on 2025-04-28 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_image_eventimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='organizer_image',
        ),
    ]
