# Generated by Django 4.2.20 on 2025-04-30 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_event_organizer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizer_image',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='events.event'),
        ),
    ]
