# Generated by Django 4.2.20 on 2025-04-30 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='slug',
        ),
    ]
