# Generated by Django 4.2.20 on 2025-05-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
