# Generated by Django 4.2.20 on 2025-05-22 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='group',
            new_name='groupId',
        ),
    ]
