# Generated by Django 4.2.20 on 2025-07-06 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_alter_group_options'),
        ('events', '0012_rename_group_event_groupid'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='groupId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='group.group'),
        ),
    ]
