# Generated by Django 4.2.20 on 2025-07-06 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_remove_group_cover_image_remove_group_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['-created_at']},
        ),
    ]
